# Generated by Django 4.0.3 on 2022-03-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedtable',
            old_name='count_pothole',
            new_name='count_objects',
        ),
    ]
