# Generated by Django 4.0.3 on 2022-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_detectionnotificationtable_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknotificationtable',
            name='type',
            field=models.CharField(choices=[('new task', 'new_task'), ('answer', 'answer'), ('close task', 'close_task')], max_length=50, verbose_name='notification type'),
        ),
    ]
