# Generated by Django 4.0.3 on 2022-03-22 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
            ],
            options={
                'verbose_name': 'Table with task category',
                'verbose_name_plural': 'Table with task categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDateTime', models.DateTimeField(auto_now=True, verbose_name='task create date and time')),
                ('leadDateTime', models.DateTimeField(blank=True, null=True, verbose_name='task lead date and time')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description of task')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='location latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='location longitude')),
                ('address', models.TextField(blank=True, null=True, verbose_name='location address')),
                ('is_done', models.BooleanField(default=False, verbose_name='Task is done or not')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='task.category', verbose_name='task category')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='task creator')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='task executor')),
            ],
            options={
                'verbose_name': 'Table with task',
                'verbose_name_plural': 'Table with tasks',
                'ordering': ('-createDateTime',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='single_task/')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task.task', verbose_name='related task')),
            ],
            options={
                'verbose_name': 'Table with task image',
                'verbose_name_plural': 'Table with task images',
            },
        ),
    ]
