# Generated by Django 4.0.3 on 2022-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDateTime', models.DateTimeField(auto_now=True, verbose_name='task create date and time')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description of task')),
            ],
        ),
    ]
