# Generated by Django 4.0.3 on 2022-03-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='leadTime',
            new_name='leadDateTime',
        ),
    ]
