# Generated by Django 4.0.3 on 2022-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_latitude_alter_task_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='location latitude'),
        ),
        migrations.AlterField(
            model_name='task',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='location longitude'),
        ),
    ]
